name: Update Open Source Contributions Portfolio
# This workflow automatically updates the portfolio with latest contribution data
# Runs daily at midnight UTC and can be triggered manually

on:
  schedule:
    # Run daily at 00:00 UTC (midnight)
    - cron: '0 0 * * *'
  
  workflow_dispatch:
    # Allow manual triggering from Actions tab
  
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/update-portfolio.yml'

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements.txt'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then
            pip install -r scripts/requirements.txt
          else
            echo "requirements.txt not found, installing common dependencies"
            pip install requests PyGithub python-dotenv
          fi
      
      - name: Fetch contribution data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          if [ -f scripts/fetch_contributions.py ]; then
            python scripts/fetch_contributions.py
          else
            echo "fetch_contributions.py not yet created, skipping..."
          fi
      
      - name: Generate statistics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          if [ -f scripts/generate_stats.py ]; then
            python scripts/generate_stats.py
          else
            echo "generate_stats.py not yet created, skipping..."
          fi
      
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          if [ -f scripts/update_readme.py ]; then
            python scripts/update_readme.py
          else
            echo "update_readme.py not yet created, skipping..."
          fi
      
      - name: Check for changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: Auto-update portfolio data [$(date +'%Y-%m-%d %H:%M:%S UTC')]"
          git push
      
      - name: Summary
        run: |
          echo "### Portfolio Update Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Successfully updated portfolio with latest contribution data" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f data/contributions.json ]; then
            echo "**Data collected:** contributions.json" >> $GITHUB_STEP_SUMMARY
          fi
